name: Generate Snake Game from GitHub Contributions

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight (UTC)
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Game from GitHub Contributions
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: ${{ github.repository_owner }}  # Your GitHub username
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
